### PR TITLE
FIX: recursion depth trap in ListWreathProductElement and WreathProductElementList

### PR DESCRIPTION
**Pull request by FriedrichRober**
The recursion works roughly as follows:
- ListWreathProductElement and WreathProductElementList both call Projection
- Projection needs to build a Homomorphism from wreath product W to top group H
- Homomorphism needs to check if elements in domain live in W
- WPE_IN checks whether element can be decomposed in W via ListWreathProductElement
- Recursion depth trap

Remove the WPE_IN check for elements of wreath product for now.

### CODE REVIEW

**Comment by FriedrichRober** [comment]
Hopefully this fixes the error blocking #63. @fingolfin, can you try it out locally on your machine, since I had troubles to reproduce it interactively in a GAP session. I hope the failing test should pass now when executed from the GAP root:
```
LoadPackage("WPE");
Test("tst/testinstall/opers/ListWreathProductElement.tst");
```
On my machine it passes now, but I don't trust it anymore.

**Comment by FriedrichRober** [comment]
The current fix is just to disable the efficient element membership test in wreath products. I have to think hard how to avoid the recursion error before even attempting to re-enable it again

**Comment by fingolfin** [comment]
Huh, this is really strange. This sounds like it should *always* run into a recursion loop, but it doesn't. Why doesn't it?

Separately, could you perhaps change `WPE_IN` to do something like this at the start:
```gap
  info := WreathProductInfo( W );
  if not IsBound( info.projection ) then TryNextMethod(); fi;
```

**Review by fingolfin — APPROVED** [review]

**Comment by FriedrichRober** [comment]
I am not sure why it doesn't always run into a loop. I will try your suggestion in new pull request. Thanks

**Pull request merged**
